// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQz5VOF5-a7rKe67oesvPZYMLmQ9U6U5M',
    appId: '1:124521540698:web:47bf115d3c2a5cedd7fc63',
    messagingSenderId: '124521540698',
    projectId: 'fcs-friend-847b9',
    authDomain: 'fcs-friend-847b9.firebaseapp.com',
    storageBucket: 'fcs-friend-847b9.appspot.com',
    measurementId: 'G-97VQQ9KDRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaKZlO8e82OEKuRm4qJoHd5x-OokYDUs',
    appId: '1:124521540698:android:a62443b463c3351ed7fc63',
    messagingSenderId: '124521540698',
    projectId: 'fcs-friend-847b9',
    storageBucket: 'fcs-friend-847b9.appspot.com',
  );
}
